const aliases: Record<string, string> = {
  "household name": "household_name",
  household: "household_name",
  "first name": "first_name",
  "last name": "last_name",
  "account type": "account_type",
  "account type ": "account_type",
  "acct type": "account_type",
  custodian: "custodian",
  "phone #": "phone",
  phone: "phone",
  "phone number": "phone",
  email: "email",
  address: "address",
  dob: "dob",
  "date of birth": "dob",
  occupation: "occupation",
  employer: "employer",
  "client tax bracket": "tax_bracket",
  "tax bracket": "tax_bracket",
  "estimated liquid net worth": "liquid_net_worth",
  "liquid net worth": "liquid_net_worth",
  "estimated total net worth": "total_net_worth",
  "total net worth": "total_net_worth",
  "annual income": "income",
  income: "income",
  "years of experience - bonds": "exp_bonds",
  "years of experience - stocks": "exp_stocks",
  "years of experience - alternatives": "exp_alternatives",
  "years of expience - vas": "exp_vas",
  "years of experience - mutual funds": "exp_mutual_funds",
  "years of experience - options": "exp_options",
  "years of experience - partnerships": "exp_partnerships",
  "primary investment objective": "investment_objective",
  "risk tolerance": "risk_tolerance",
  "time horizon": "time_horizon",
  "account decision making": "decision_making",
  "source of funds": "source_of_funds",
  "primary use of funds": "primary_use",
  "liquidity needs": "liquidity_needs",
  "liquidity time horizon": "liquidity_horizon",
  "marital status": "marital_status",
  "marital status ": "marital_status",
  "bank name": "bank_name",
  "bank type - checking/savings": "bank_type",
  "account no": "bank_account_number",
  "beneficiary 1 name": "beneficiary_1_name",
  "beneficiary 1  %": "beneficiary_1_pct",
  "beneficiary 1 %": "beneficiary_1_pct",
  "beneficiary 1 dob": "beneficiary_1_dob",
  "beneficiary 2 name": "beneficiary_2_name",
  "beneficiary 2 %": "beneficiary_2_pct",
  "beneficiary 2 dob": "beneficiary_2_dob",
};

export function canonicalHeader(rawHeader: string) {
  const key = rawHeader.trim().toLowerCase();
  return aliases[key] ?? key.replace(/\s+/g, "_");
}

export const requiredHouseholdHeaders = new Set([
  "household_name",
  "first_name",
  "last_name",
  "account_type",
]);
